<?php
/**
 * MessageObject
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>The preferred way is to use https://api.unione.io/en/transactional/api/v1 endpoint, but also you can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly, depending on the host your account was registered at.
 *
 * The version of the OpenAPI document: 1.76
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Model;

use \ArrayAccess;
use \UniOne\ObjectSerializer;

/**
 * MessageObject Class Doc Comment
 *
 * @category Class
 * @description Object containing all message properties.
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MessageObject implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MessageObject';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'recipients' => '\UniOne\Model\MessageObjectRecipientsInner[]',
        'templateId' => 'string',
        'tags' => 'string[]',
        'skipUnsubscribe' => 'int',
        'globalLanguage' => 'string',
        'templateEngine' => '\UniOne\Model\TemplateEngineString',
        'globalSubstitutions' => 'array<string,string>',
        'globalMetadata' => 'array<string,string>',
        'body' => '\UniOne\Model\BodyObject',
        'subject' => 'string',
        'fromEmail' => 'string',
        'fromName' => 'string',
        'replyTo' => 'string',
        'replyToName' => 'string',
        'trackLinks' => '\UniOne\Model\TrackLinksInteger',
        'trackRead' => '\UniOne\Model\TrackReadInteger',
        'bypassGlobal' => '\UniOne\Model\BypassGlobalInteger',
        'bypassUnavailable' => '\UniOne\Model\BypassUnavailableInteger',
        'bypassUnsubscribed' => '\UniOne\Model\BypassUnsubscribedInteger',
        'bypassComplained' => '\UniOne\Model\BypassComplainedInteger',
        'idempotenceKey' => 'string',
        'headers' => '\UniOne\Model\HeadersObject',
        'attachments' => '\UniOne\Model\AttachmentsArrayInner[]',
        'inlineAttachments' => '\UniOne\Model\InlineAttachmentsArrayInner[]',
        'options' => '\UniOne\Model\MessageObjectOptions'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'recipients' => null,
        'templateId' => 'uuid',
        'tags' => null,
        'skipUnsubscribe' => null,
        'globalLanguage' => null,
        'templateEngine' => null,
        'globalSubstitutions' => null,
        'globalMetadata' => null,
        'body' => null,
        'subject' => null,
        'fromEmail' => 'email',
        'fromName' => null,
        'replyTo' => 'email',
        'replyToName' => null,
        'trackLinks' => null,
        'trackRead' => null,
        'bypassGlobal' => null,
        'bypassUnavailable' => null,
        'bypassUnsubscribed' => null,
        'bypassComplained' => null,
        'idempotenceKey' => null,
        'headers' => null,
        'attachments' => null,
        'inlineAttachments' => null,
        'options' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'recipients' => false,
        'templateId' => false,
        'tags' => false,
        'skipUnsubscribe' => false,
        'globalLanguage' => false,
        'templateEngine' => false,
        'globalSubstitutions' => false,
        'globalMetadata' => false,
        'body' => false,
        'subject' => false,
        'fromEmail' => false,
        'fromName' => false,
        'replyTo' => false,
        'replyToName' => false,
        'trackLinks' => false,
        'trackRead' => false,
        'bypassGlobal' => false,
        'bypassUnavailable' => false,
        'bypassUnsubscribed' => false,
        'bypassComplained' => false,
        'idempotenceKey' => false,
        'headers' => false,
        'attachments' => false,
        'inlineAttachments' => false,
        'options' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'recipients' => 'recipients',
        'templateId' => 'template_id',
        'tags' => 'tags',
        'skipUnsubscribe' => 'skip_unsubscribe',
        'globalLanguage' => 'global_language',
        'templateEngine' => 'template_engine',
        'globalSubstitutions' => 'global_substitutions',
        'globalMetadata' => 'global_metadata',
        'body' => 'body',
        'subject' => 'subject',
        'fromEmail' => 'from_email',
        'fromName' => 'from_name',
        'replyTo' => 'reply_to',
        'replyToName' => 'reply_to_name',
        'trackLinks' => 'track_links',
        'trackRead' => 'track_read',
        'bypassGlobal' => 'bypass_global',
        'bypassUnavailable' => 'bypass_unavailable',
        'bypassUnsubscribed' => 'bypass_unsubscribed',
        'bypassComplained' => 'bypass_complained',
        'idempotenceKey' => 'idempotence_key',
        'headers' => 'headers',
        'attachments' => 'attachments',
        'inlineAttachments' => 'inline_attachments',
        'options' => 'options'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'recipients' => 'setRecipients',
        'templateId' => 'setTemplateId',
        'tags' => 'setTags',
        'skipUnsubscribe' => 'setSkipUnsubscribe',
        'globalLanguage' => 'setGlobalLanguage',
        'templateEngine' => 'setTemplateEngine',
        'globalSubstitutions' => 'setGlobalSubstitutions',
        'globalMetadata' => 'setGlobalMetadata',
        'body' => 'setBody',
        'subject' => 'setSubject',
        'fromEmail' => 'setFromEmail',
        'fromName' => 'setFromName',
        'replyTo' => 'setReplyTo',
        'replyToName' => 'setReplyToName',
        'trackLinks' => 'setTrackLinks',
        'trackRead' => 'setTrackRead',
        'bypassGlobal' => 'setBypassGlobal',
        'bypassUnavailable' => 'setBypassUnavailable',
        'bypassUnsubscribed' => 'setBypassUnsubscribed',
        'bypassComplained' => 'setBypassComplained',
        'idempotenceKey' => 'setIdempotenceKey',
        'headers' => 'setHeaders',
        'attachments' => 'setAttachments',
        'inlineAttachments' => 'setInlineAttachments',
        'options' => 'setOptions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'recipients' => 'getRecipients',
        'templateId' => 'getTemplateId',
        'tags' => 'getTags',
        'skipUnsubscribe' => 'getSkipUnsubscribe',
        'globalLanguage' => 'getGlobalLanguage',
        'templateEngine' => 'getTemplateEngine',
        'globalSubstitutions' => 'getGlobalSubstitutions',
        'globalMetadata' => 'getGlobalMetadata',
        'body' => 'getBody',
        'subject' => 'getSubject',
        'fromEmail' => 'getFromEmail',
        'fromName' => 'getFromName',
        'replyTo' => 'getReplyTo',
        'replyToName' => 'getReplyToName',
        'trackLinks' => 'getTrackLinks',
        'trackRead' => 'getTrackRead',
        'bypassGlobal' => 'getBypassGlobal',
        'bypassUnavailable' => 'getBypassUnavailable',
        'bypassUnsubscribed' => 'getBypassUnsubscribed',
        'bypassComplained' => 'getBypassComplained',
        'idempotenceKey' => 'getIdempotenceKey',
        'headers' => 'getHeaders',
        'attachments' => 'getAttachments',
        'inlineAttachments' => 'getInlineAttachments',
        'options' => 'getOptions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SKIP_UNSUBSCRIBE_NUMBER_0 = 0;
    public const SKIP_UNSUBSCRIBE_NUMBER_1 = 1;
    public const SKIP_UNSUBSCRIBE_UNKNOWN_DEFAULT_OPEN_API = 11184809;

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSkipUnsubscribeAllowableValues()
    {
        return [
            self::SKIP_UNSUBSCRIBE_NUMBER_0,
            self::SKIP_UNSUBSCRIBE_NUMBER_1,
            self::SKIP_UNSUBSCRIBE_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('recipients', $data ?? [], null);
        $this->setIfExists('templateId', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('skipUnsubscribe', $data ?? [], null);
        $this->setIfExists('globalLanguage', $data ?? [], null);
        $this->setIfExists('templateEngine', $data ?? [], null);
        $this->setIfExists('globalSubstitutions', $data ?? [], null);
        $this->setIfExists('globalMetadata', $data ?? [], null);
        $this->setIfExists('body', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('fromEmail', $data ?? [], null);
        $this->setIfExists('fromName', $data ?? [], null);
        $this->setIfExists('replyTo', $data ?? [], null);
        $this->setIfExists('replyToName', $data ?? [], null);
        $this->setIfExists('trackLinks', $data ?? [], null);
        $this->setIfExists('trackRead', $data ?? [], null);
        $this->setIfExists('bypassGlobal', $data ?? [], null);
        $this->setIfExists('bypassUnavailable', $data ?? [], null);
        $this->setIfExists('bypassUnsubscribed', $data ?? [], null);
        $this->setIfExists('bypassComplained', $data ?? [], null);
        $this->setIfExists('idempotenceKey', $data ?? [], null);
        $this->setIfExists('headers', $data ?? [], null);
        $this->setIfExists('attachments', $data ?? [], null);
        $this->setIfExists('inlineAttachments', $data ?? [], null);
        $this->setIfExists('options', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['recipients'] === null) {
            $invalidProperties[] = "'recipients' can't be null";
        }
        $allowedValues = $this->getSkipUnsubscribeAllowableValues();
        if (!is_null($this->container['skipUnsubscribe']) && !in_array($this->container['skipUnsubscribe'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'skipUnsubscribe', must be one of '%s'",
                $this->container['skipUnsubscribe'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['body'] === null) {
            $invalidProperties[] = "'body' can't be null";
        }
        if ($this->container['subject'] === null) {
            $invalidProperties[] = "'subject' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets recipients
     *
     * @return \UniOne\Model\MessageObjectRecipientsInner[]
     */
    public function getRecipients()
    {
        return $this->container['recipients'];
    }

    /**
     * Sets recipients
     *
     * @param \UniOne\Model\MessageObjectRecipientsInner[] $recipients Contains recipient emails, substitutions(merge tags) and metadata.
     *
     * @return self
     */
    public function setRecipients($recipients)
    {
        if (is_null($recipients)) {
            throw new \InvalidArgumentException('non-nullable recipients cannot be null');
        }
        $this->container['recipients'] = $recipients;

        return $this;
    }

    /**
     * Gets templateId
     *
     * @return string|null
     */
    public function getTemplateId()
    {
        return $this->container['templateId'];
    }

    /**
     * Sets templateId
     *
     * @param string|null $templateId Optional identifier of the template that had been created by [template/set](https://docs.unione.io/en/web-api-ref#template-set) method. If template_id is passed then fields from the template are used instead of missed email/send parameters. E.g. if **body** parameter in email/send is omitted, **body** from template will be used. If **subject** in email/send is omitted, **subject** from template will be used.
     *
     * @return self
     */
    public function setTemplateId($templateId)
    {
        if (is_null($templateId)) {
            throw new \InvalidArgumentException('non-nullable templateId cannot be null');
        }
        $this->container['templateId'] = $templateId;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags An array of strings. The maximum string length is 50 characters. You can include up to 4 strings which must be unique. No more than 10 000 tags are allowed per project; if you try to add more, email/send will return an error. You may use tags to categorize emails by your own criteria, and they will be passed along by event-dump methods.
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets skipUnsubscribe
     *
     * @return int|null
     */
    public function getSkipUnsubscribe()
    {
        return $this->container['skipUnsubscribe'];
    }

    /**
     * Sets skipUnsubscribe
     *
     * @param int|null $skipUnsubscribe Whether to skip or not appending default unsubscribe footer. 1=skip, 0=append, default is 0. You should [ask support](https://cp.unione.io/en/support) to approve<br>usage of skip_unsubscribe=1. [Read more](https://docs.unione.io/en/unsubscribe-link).
     *
     * @return self
     */
    public function setSkipUnsubscribe($skipUnsubscribe)
    {
        if (is_null($skipUnsubscribe)) {
            throw new \InvalidArgumentException('non-nullable skipUnsubscribe cannot be null');
        }
        $allowedValues = $this->getSkipUnsubscribeAllowableValues();
        if (!in_array($skipUnsubscribe, $allowedValues, true)) {
            $skipUnsubscribe = self::SKIP_UNSUBSCRIBE_UNKNOWN_DEFAULT_OPEN_API;
        }
        $this->container['skipUnsubscribe'] = $skipUnsubscribe;

        return $this;
    }

    /**
     * Gets globalLanguage
     *
     * @return string|null
     */
    public function getGlobalLanguage()
    {
        return $this->container['globalLanguage'];
    }

    /**
     * Sets globalLanguage
     *
     * @param string|null $globalLanguage The language of the unsubscribe footer and unsubscribe page. Languages supported are: **be**, **de**, **en**, **es**, **fr**, **it**, **pl**, **pt**, **ru**, **ua**, **kz**.
     *
     * @return self
     */
    public function setGlobalLanguage($globalLanguage)
    {
        if (is_null($globalLanguage)) {
            throw new \InvalidArgumentException('non-nullable globalLanguage cannot be null');
        }
        $this->container['globalLanguage'] = $globalLanguage;

        return $this;
    }

    /**
     * Gets templateEngine
     *
     * @return \UniOne\Model\TemplateEngineString|null
     */
    public function getTemplateEngine()
    {
        return $this->container['templateEngine'];
    }

    /**
     * Sets templateEngine
     *
     * @param \UniOne\Model\TemplateEngineString|null $templateEngine templateEngine
     *
     * @return self
     */
    public function setTemplateEngine($templateEngine)
    {
        if (is_null($templateEngine)) {
            throw new \InvalidArgumentException('non-nullable templateEngine cannot be null');
        }
        $this->container['templateEngine'] = $templateEngine;

        return $this;
    }

    /**
     * Gets globalSubstitutions
     *
     * @return array<string,string>|null
     */
    public function getGlobalSubstitutions()
    {
        return $this->container['globalSubstitutions'];
    }

    /**
     * Sets globalSubstitutions
     *
     * @param array<string,string>|null $globalSubstitutions Object for passing the substitutions(merge tags) common for all recipients - e.g., company name. If the substitution names are duplicated in object **substitutions**, the values of the variables will be taken from the object **substitutions**. The substitutions can be used in the following parameters:<br><br>* body.html* body.plaintext* body.amp* subject* from_name* options.unsubscribe_url<br><br>A substitution name can consist from latin characeters, numbers and **_** symbol, and should start with the letter.
     *
     * @return self
     */
    public function setGlobalSubstitutions($globalSubstitutions)
    {
        if (is_null($globalSubstitutions)) {
            throw new \InvalidArgumentException('non-nullable globalSubstitutions cannot be null');
        }
        $this->container['globalSubstitutions'] = $globalSubstitutions;

        return $this;
    }

    /**
     * Gets globalMetadata
     *
     * @return array<string,string>|null
     */
    public function getGlobalMetadata()
    {
        return $this->container['globalMetadata'];
    }

    /**
     * Sets globalMetadata
     *
     * @param array<string,string>|null $globalMetadata Object for passing the metadata common for all the recipients, such as **key**: **value**. Max key quantity: 10. Max key length: 64 symbols. Max value length: 1024 symbols. The metadata is returned by [webhook](https://docs.unione.io/en/web-api-ref#webhook). To group single emails into a campaign, you can use the system key 'campaign_id' with a value in the form of a non-negative decimal integer up to 128 bits or a UUID in the format 'c7703772-453e-4c77-a9ae-9a1b94051b5a'. Incorrect values will be treated as '0'.
     *
     * @return self
     */
    public function setGlobalMetadata($globalMetadata)
    {
        if (is_null($globalMetadata)) {
            throw new \InvalidArgumentException('non-nullable globalMetadata cannot be null');
        }
        $this->container['globalMetadata'] = $globalMetadata;

        return $this;
    }

    /**
     * Gets body
     *
     * @return \UniOne\Model\BodyObject
     */
    public function getBody()
    {
        return $this->container['body'];
    }

    /**
     * Sets body
     *
     * @param \UniOne\Model\BodyObject $body body
     *
     * @return self
     */
    public function setBody($body)
    {
        if (is_null($body)) {
            throw new \InvalidArgumentException('non-nullable body cannot be null');
        }
        $this->container['body'] = $body;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string $subject Email subject.
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets fromEmail
     *
     * @return string|null
     */
    public function getFromEmail()
    {
        return $this->container['fromEmail'];
    }

    /**
     * Sets fromEmail
     *
     * @param string|null $fromEmail Sender's email. Required only if template_id parameter is empty.
     *
     * @return self
     */
    public function setFromEmail($fromEmail)
    {
        if (is_null($fromEmail)) {
            throw new \InvalidArgumentException('non-nullable fromEmail cannot be null');
        }
        $this->container['fromEmail'] = $fromEmail;

        return $this;
    }

    /**
     * Gets fromName
     *
     * @return string|null
     */
    public function getFromName()
    {
        return $this->container['fromName'];
    }

    /**
     * Sets fromName
     *
     * @param string|null $fromName Sender's name.
     *
     * @return self
     */
    public function setFromName($fromName)
    {
        if (is_null($fromName)) {
            throw new \InvalidArgumentException('non-nullable fromName cannot be null');
        }
        $this->container['fromName'] = $fromName;

        return $this;
    }

    /**
     * Gets replyTo
     *
     * @return string|null
     */
    public function getReplyTo()
    {
        return $this->container['replyTo'];
    }

    /**
     * Sets replyTo
     *
     * @param string|null $replyTo Optional Reply-To email (in case it's different to sender's email)
     *
     * @return self
     */
    public function setReplyTo($replyTo)
    {
        if (is_null($replyTo)) {
            throw new \InvalidArgumentException('non-nullable replyTo cannot be null');
        }
        $this->container['replyTo'] = $replyTo;

        return $this;
    }

    /**
     * Gets replyToName
     *
     * @return string|null
     */
    public function getReplyToName()
    {
        return $this->container['replyToName'];
    }

    /**
     * Sets replyToName
     *
     * @param string|null $replyToName Optional Reply-To name (if reply_to email is specified and you want to display not only this email but also the name)
     *
     * @return self
     */
    public function setReplyToName($replyToName)
    {
        if (is_null($replyToName)) {
            throw new \InvalidArgumentException('non-nullable replyToName cannot be null');
        }
        $this->container['replyToName'] = $replyToName;

        return $this;
    }

    /**
     * Gets trackLinks
     *
     * @return \UniOne\Model\TrackLinksInteger|null
     */
    public function getTrackLinks()
    {
        return $this->container['trackLinks'];
    }

    /**
     * Sets trackLinks
     *
     * @param \UniOne\Model\TrackLinksInteger|null $trackLinks trackLinks
     *
     * @return self
     */
    public function setTrackLinks($trackLinks)
    {
        if (is_null($trackLinks)) {
            throw new \InvalidArgumentException('non-nullable trackLinks cannot be null');
        }
        $this->container['trackLinks'] = $trackLinks;

        return $this;
    }

    /**
     * Gets trackRead
     *
     * @return \UniOne\Model\TrackReadInteger|null
     */
    public function getTrackRead()
    {
        return $this->container['trackRead'];
    }

    /**
     * Sets trackRead
     *
     * @param \UniOne\Model\TrackReadInteger|null $trackRead trackRead
     *
     * @return self
     */
    public function setTrackRead($trackRead)
    {
        if (is_null($trackRead)) {
            throw new \InvalidArgumentException('non-nullable trackRead cannot be null');
        }
        $this->container['trackRead'] = $trackRead;

        return $this;
    }

    /**
     * Gets bypassGlobal
     *
     * @return \UniOne\Model\BypassGlobalInteger|null
     */
    public function getBypassGlobal()
    {
        return $this->container['bypassGlobal'];
    }

    /**
     * Sets bypassGlobal
     *
     * @param \UniOne\Model\BypassGlobalInteger|null $bypassGlobal bypassGlobal
     *
     * @return self
     */
    public function setBypassGlobal($bypassGlobal)
    {
        if (is_null($bypassGlobal)) {
            throw new \InvalidArgumentException('non-nullable bypassGlobal cannot be null');
        }
        $this->container['bypassGlobal'] = $bypassGlobal;

        return $this;
    }

    /**
     * Gets bypassUnavailable
     *
     * @return \UniOne\Model\BypassUnavailableInteger|null
     */
    public function getBypassUnavailable()
    {
        return $this->container['bypassUnavailable'];
    }

    /**
     * Sets bypassUnavailable
     *
     * @param \UniOne\Model\BypassUnavailableInteger|null $bypassUnavailable bypassUnavailable
     *
     * @return self
     */
    public function setBypassUnavailable($bypassUnavailable)
    {
        if (is_null($bypassUnavailable)) {
            throw new \InvalidArgumentException('non-nullable bypassUnavailable cannot be null');
        }
        $this->container['bypassUnavailable'] = $bypassUnavailable;

        return $this;
    }

    /**
     * Gets bypassUnsubscribed
     *
     * @return \UniOne\Model\BypassUnsubscribedInteger|null
     */
    public function getBypassUnsubscribed()
    {
        return $this->container['bypassUnsubscribed'];
    }

    /**
     * Sets bypassUnsubscribed
     *
     * @param \UniOne\Model\BypassUnsubscribedInteger|null $bypassUnsubscribed bypassUnsubscribed
     *
     * @return self
     */
    public function setBypassUnsubscribed($bypassUnsubscribed)
    {
        if (is_null($bypassUnsubscribed)) {
            throw new \InvalidArgumentException('non-nullable bypassUnsubscribed cannot be null');
        }
        $this->container['bypassUnsubscribed'] = $bypassUnsubscribed;

        return $this;
    }

    /**
     * Gets bypassComplained
     *
     * @return \UniOne\Model\BypassComplainedInteger|null
     */
    public function getBypassComplained()
    {
        return $this->container['bypassComplained'];
    }

    /**
     * Sets bypassComplained
     *
     * @param \UniOne\Model\BypassComplainedInteger|null $bypassComplained bypassComplained
     *
     * @return self
     */
    public function setBypassComplained($bypassComplained)
    {
        if (is_null($bypassComplained)) {
            throw new \InvalidArgumentException('non-nullable bypassComplained cannot be null');
        }
        $this->container['bypassComplained'] = $bypassComplained;

        return $this;
    }

    /**
     * Gets idempotenceKey
     *
     * @return string|null
     */
    public function getIdempotenceKey()
    {
        return $this->container['idempotenceKey'];
    }

    /**
     * Sets idempotenceKey
     *
     * @param string|null $idempotenceKey A string of up to 64 characters containing a unique message key. This can be used to prevent occasional message duplicates. If you send another API request with the same message key within the next minute, it will be declined. We can generate a message key for each letter automatically; to enable this option, please contact our [tech support](https://cp.unione.io/en/support).
     *
     * @return self
     */
    public function setIdempotenceKey($idempotenceKey)
    {
        if (is_null($idempotenceKey)) {
            throw new \InvalidArgumentException('non-nullable idempotenceKey cannot be null');
        }
        $this->container['idempotenceKey'] = $idempotenceKey;

        return $this;
    }

    /**
     * Gets headers
     *
     * @return \UniOne\Model\HeadersObject|null
     */
    public function getHeaders()
    {
        return $this->container['headers'];
    }

    /**
     * Sets headers
     *
     * @param \UniOne\Model\HeadersObject|null $headers headers
     *
     * @return self
     */
    public function setHeaders($headers)
    {
        if (is_null($headers)) {
            throw new \InvalidArgumentException('non-nullable headers cannot be null');
        }
        $this->container['headers'] = $headers;

        return $this;
    }

    /**
     * Gets attachments
     *
     * @return \UniOne\Model\AttachmentsArrayInner[]|null
     */
    public function getAttachments()
    {
        return $this->container['attachments'];
    }

    /**
     * Sets attachments
     *
     * @param \UniOne\Model\AttachmentsArrayInner[]|null $attachments Optional array of attachments
     *
     * @return self
     */
    public function setAttachments($attachments)
    {
        if (is_null($attachments)) {
            throw new \InvalidArgumentException('non-nullable attachments cannot be null');
        }
        $this->container['attachments'] = $attachments;

        return $this;
    }

    /**
     * Gets inlineAttachments
     *
     * @return \UniOne\Model\InlineAttachmentsArrayInner[]|null
     */
    public function getInlineAttachments()
    {
        return $this->container['inlineAttachments'];
    }

    /**
     * Sets inlineAttachments
     *
     * @param \UniOne\Model\InlineAttachmentsArrayInner[]|null $inlineAttachments Optional array of inline attachments, e.g. for including images in email instead of loading them from external URL.
     *
     * @return self
     */
    public function setInlineAttachments($inlineAttachments)
    {
        if (is_null($inlineAttachments)) {
            throw new \InvalidArgumentException('non-nullable inlineAttachments cannot be null');
        }
        $this->container['inlineAttachments'] = $inlineAttachments;

        return $this;
    }

    /**
     * Gets options
     *
     * @return \UniOne\Model\MessageObjectOptions|null
     */
    public function getOptions()
    {
        return $this->container['options'];
    }

    /**
     * Sets options
     *
     * @param \UniOne\Model\MessageObjectOptions|null $options options
     *
     * @return self
     */
    public function setOptions($options)
    {
        if (is_null($options)) {
            throw new \InvalidArgumentException('non-nullable options cannot be null');
        }
        $this->container['options'] = $options;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


