<?php
/**
 * ProjectObject
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>The preferred way is to use https://api.unione.io/en/transactional/api/v1 endpoint, but also you can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly, depending on the host your account was registered at.
 *
 * The version of the OpenAPI document: 1.76
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Model;

use \ArrayAccess;
use \UniOne\ObjectSerializer;

/**
 * ProjectObject Class Doc Comment
 *
 * @category Class
 * @description Object with project properties.
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProjectObject implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProjectObject';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'country' => 'string',
        'sendEnabled' => 'bool',
        'customUnsubscribeUrlEnabled' => 'bool',
        'backendDomainId' => 'int',
        'unsubscribePageId' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'country' => null,
        'sendEnabled' => null,
        'customUnsubscribeUrlEnabled' => null,
        'backendDomainId' => null,
        'unsubscribePageId' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'country' => false,
        'sendEnabled' => false,
        'customUnsubscribeUrlEnabled' => false,
        'backendDomainId' => false,
        'unsubscribePageId' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'country' => 'country',
        'sendEnabled' => 'send_enabled',
        'customUnsubscribeUrlEnabled' => 'custom_unsubscribe_url_enabled',
        'backendDomainId' => 'backend_domain_id',
        'unsubscribePageId' => 'unsubscribe_page_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'country' => 'setCountry',
        'sendEnabled' => 'setSendEnabled',
        'customUnsubscribeUrlEnabled' => 'setCustomUnsubscribeUrlEnabled',
        'backendDomainId' => 'setBackendDomainId',
        'unsubscribePageId' => 'setUnsubscribePageId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'country' => 'getCountry',
        'sendEnabled' => 'getSendEnabled',
        'customUnsubscribeUrlEnabled' => 'getCustomUnsubscribeUrlEnabled',
        'backendDomainId' => 'getBackendDomainId',
        'unsubscribePageId' => 'getUnsubscribePageId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('sendEnabled', $data ?? [], true);
        $this->setIfExists('customUnsubscribeUrlEnabled', $data ?? [], null);
        $this->setIfExists('backendDomainId', $data ?? [], null);
        $this->setIfExists('unsubscribePageId', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Project name, unique for user account.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country ISO-3166 alpha-2 country code. If set, UniOne treats project personal data according to country laws, e.g. GDPR for european countries.
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets sendEnabled
     *
     * @return bool|null
     */
    public function getSendEnabled()
    {
        return $this->container['sendEnabled'];
    }

    /**
     * Sets sendEnabled
     *
     * @param bool|null $sendEnabled Whether email sending is enabled for this project or not.
     *
     * @return self
     */
    public function setSendEnabled($sendEnabled)
    {
        if (is_null($sendEnabled)) {
            throw new \InvalidArgumentException('non-nullable sendEnabled cannot be null');
        }
        $this->container['sendEnabled'] = $sendEnabled;

        return $this;
    }

    /**
     * Gets customUnsubscribeUrlEnabled
     *
     * @return bool|null
     */
    public function getCustomUnsubscribeUrlEnabled()
    {
        return $this->container['customUnsubscribeUrlEnabled'];
    }

    /**
     * Sets customUnsubscribeUrlEnabled
     *
     * @param bool|null $customUnsubscribeUrlEnabled If it's false then UniOne adds default unsubscribe footer to each email sent with API key of the project. If it's true then appending default unsubscribe footer for this project is avoided and sending with custom unsubscribe url or even without unsubscribe url is permitted for the project. Please note that custom_unsubscribe_url_enabled=true is available only if removing unsubscribe link is approved for the user account by support. More on this [here](https://docs.unione.io/en/unsubscribe-link). When custom_unsubscribe_url_enabled is skipped on creating a project, it's value is taken from user
     *
     * @return self
     */
    public function setCustomUnsubscribeUrlEnabled($customUnsubscribeUrlEnabled)
    {
        if (is_null($customUnsubscribeUrlEnabled)) {
            throw new \InvalidArgumentException('non-nullable customUnsubscribeUrlEnabled cannot be null');
        }
        $this->container['customUnsubscribeUrlEnabled'] = $customUnsubscribeUrlEnabled;

        return $this;
    }

    /**
     * Gets backendDomainId
     *
     * @return int|null
     */
    public function getBackendDomainId()
    {
        return $this->container['backendDomainId'];
    }

    /**
     * Sets backendDomainId
     *
     * @param int|null $backendDomainId A unique domain identifier which will determine the [tracking domain](https://docs.unione.io/en/tracking-domains) or [dedicated IP](/dedicated-ip) pool to be used by default. If the value is not specified, a default backend domain will be assigned for your account or project instead.
     *
     * @return self
     */
    public function setBackendDomainId($backendDomainId)
    {
        if (is_null($backendDomainId)) {
            throw new \InvalidArgumentException('non-nullable backendDomainId cannot be null');
        }
        $this->container['backendDomainId'] = $backendDomainId;

        return $this;
    }

    /**
     * Gets unsubscribePageId
     *
     * @return int|null
     */
    public function getUnsubscribePageId()
    {
        return $this->container['unsubscribePageId'];
    }

    /**
     * Sets unsubscribePageId
     *
     * @param int|null $unsubscribePageId A unique identifier that defines the default unsubscribe page. If absent, the account/project will be assigned the system default unsubscribe page.
     *
     * @return self
     */
    public function setUnsubscribePageId($unsubscribePageId)
    {
        if (is_null($unsubscribePageId)) {
            throw new \InvalidArgumentException('non-nullable unsubscribePageId cannot be null');
        }
        $this->container['unsubscribePageId'] = $unsubscribePageId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


