<?php
/**
 * TemplateEngineString
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>The preferred way is to use https://api.unione.io/en/transactional/api/v1 endpoint, but also you can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly, depending on the host your account was registered at.
 *
 * The version of the OpenAPI document: 1.76
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Model;
use \UniOne\ObjectSerializer;

/**
 * TemplateEngineString Class Doc Comment
 *
 * @category Class
 * @description The [template engine](https://docs.unione.io/en/template-engines) for handling the substitutions(merge tags), **simple**, **velocity**, **liquid** or **none**. Default value is **simple**.
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TemplateEngineString
{
    /**
     * Possible values of this enum
     */
    public const SIMPLE = 'simple';

    public const VELOCITY = 'velocity';

    public const LIQUID = 'liquid';

    public const NONE = 'none';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SIMPLE,
            self::VELOCITY,
            self::LIQUID,
            self::NONE,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}


