<?php
/**
 * TemplateListObject
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>The preferred way is to use https://api.unione.io/en/transactional/api/v1 endpoint, but also you can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly, depending on the host your account was registered at.
 *
 * The version of the OpenAPI document: 1.76
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Model;

use \ArrayAccess;
use \UniOne\ObjectSerializer;

/**
 * TemplateListObject Class Doc Comment
 *
 * @category Class
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TemplateListObject implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TemplateListObject';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'editorType' => '\UniOne\Model\EditorTypeString',
        'templateEngine' => '\UniOne\Model\TemplateEngineString',
        'globalSubstitutions' => 'array<string,string>',
        'globalMetadata' => 'array<string,string>',
        'body' => '\UniOne\Model\BodyObject',
        'subject' => 'string',
        'fromEmail' => 'string',
        'fromName' => 'string',
        'replyTo' => 'string',
        'replyToName' => 'string',
        'trackLinks' => '\UniOne\Model\TrackLinksInteger',
        'trackRead' => '\UniOne\Model\TrackReadInteger',
        'headers' => '\UniOne\Model\HeadersObject',
        'attachments' => '\UniOne\Model\AttachmentsArrayInner[]',
        'inlineAttachments' => '\UniOne\Model\InlineAttachmentsArrayInner[]',
        'created' => 'string',
        'userId' => 'int',
        'projectId' => 'string',
        'projectName' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'name' => null,
        'editorType' => null,
        'templateEngine' => null,
        'globalSubstitutions' => null,
        'globalMetadata' => null,
        'body' => null,
        'subject' => null,
        'fromEmail' => 'email',
        'fromName' => null,
        'replyTo' => 'email',
        'replyToName' => null,
        'trackLinks' => null,
        'trackRead' => null,
        'headers' => null,
        'attachments' => null,
        'inlineAttachments' => null,
        'created' => 'utc-date-time',
        'userId' => null,
        'projectId' => null,
        'projectName' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'editorType' => false,
        'templateEngine' => false,
        'globalSubstitutions' => false,
        'globalMetadata' => false,
        'body' => false,
        'subject' => false,
        'fromEmail' => false,
        'fromName' => false,
        'replyTo' => false,
        'replyToName' => false,
        'trackLinks' => false,
        'trackRead' => false,
        'headers' => false,
        'attachments' => false,
        'inlineAttachments' => false,
        'created' => false,
        'userId' => false,
        'projectId' => false,
        'projectName' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'editorType' => 'editor_type',
        'templateEngine' => 'template_engine',
        'globalSubstitutions' => 'global_substitutions',
        'globalMetadata' => 'global_metadata',
        'body' => 'body',
        'subject' => 'subject',
        'fromEmail' => 'from_email',
        'fromName' => 'from_name',
        'replyTo' => 'reply_to',
        'replyToName' => 'reply_to_name',
        'trackLinks' => 'track_links',
        'trackRead' => 'track_read',
        'headers' => 'headers',
        'attachments' => 'attachments',
        'inlineAttachments' => 'inline_attachments',
        'created' => 'created',
        'userId' => 'user_id',
        'projectId' => 'project_id',
        'projectName' => 'project_name'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'editorType' => 'setEditorType',
        'templateEngine' => 'setTemplateEngine',
        'globalSubstitutions' => 'setGlobalSubstitutions',
        'globalMetadata' => 'setGlobalMetadata',
        'body' => 'setBody',
        'subject' => 'setSubject',
        'fromEmail' => 'setFromEmail',
        'fromName' => 'setFromName',
        'replyTo' => 'setReplyTo',
        'replyToName' => 'setReplyToName',
        'trackLinks' => 'setTrackLinks',
        'trackRead' => 'setTrackRead',
        'headers' => 'setHeaders',
        'attachments' => 'setAttachments',
        'inlineAttachments' => 'setInlineAttachments',
        'created' => 'setCreated',
        'userId' => 'setUserId',
        'projectId' => 'setProjectId',
        'projectName' => 'setProjectName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'editorType' => 'getEditorType',
        'templateEngine' => 'getTemplateEngine',
        'globalSubstitutions' => 'getGlobalSubstitutions',
        'globalMetadata' => 'getGlobalMetadata',
        'body' => 'getBody',
        'subject' => 'getSubject',
        'fromEmail' => 'getFromEmail',
        'fromName' => 'getFromName',
        'replyTo' => 'getReplyTo',
        'replyToName' => 'getReplyToName',
        'trackLinks' => 'getTrackLinks',
        'trackRead' => 'getTrackRead',
        'headers' => 'getHeaders',
        'attachments' => 'getAttachments',
        'inlineAttachments' => 'getInlineAttachments',
        'created' => 'getCreated',
        'userId' => 'getUserId',
        'projectId' => 'getProjectId',
        'projectName' => 'getProjectName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('editorType', $data ?? [], null);
        $this->setIfExists('templateEngine', $data ?? [], null);
        $this->setIfExists('globalSubstitutions', $data ?? [], null);
        $this->setIfExists('globalMetadata', $data ?? [], null);
        $this->setIfExists('body', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('fromEmail', $data ?? [], null);
        $this->setIfExists('fromName', $data ?? [], null);
        $this->setIfExists('replyTo', $data ?? [], null);
        $this->setIfExists('replyToName', $data ?? [], null);
        $this->setIfExists('trackLinks', $data ?? [], null);
        $this->setIfExists('trackRead', $data ?? [], null);
        $this->setIfExists('headers', $data ?? [], null);
        $this->setIfExists('attachments', $data ?? [], null);
        $this->setIfExists('inlineAttachments', $data ?? [], null);
        $this->setIfExists('created', $data ?? [], null);
        $this->setIfExists('userId', $data ?? [], null);
        $this->setIfExists('projectId', $data ?? [], null);
        $this->setIfExists('projectName', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['body'] === null) {
            $invalidProperties[] = "'body' can't be null";
        }
        if ($this->container['fromEmail'] === null) {
            $invalidProperties[] = "'fromEmail' can't be null";
        }
        if ($this->container['created'] === null) {
            $invalidProperties[] = "'created' can't be null";
        }
        if ($this->container['userId'] === null) {
            $invalidProperties[] = "'userId' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Template unique identifier.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Template name.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets editorType
     *
     * @return \UniOne\Model\EditorTypeString|null
     */
    public function getEditorType()
    {
        return $this->container['editorType'];
    }

    /**
     * Sets editorType
     *
     * @param \UniOne\Model\EditorTypeString|null $editorType editorType
     *
     * @return self
     */
    public function setEditorType($editorType)
    {
        if (is_null($editorType)) {
            throw new \InvalidArgumentException('non-nullable editorType cannot be null');
        }
        $this->container['editorType'] = $editorType;

        return $this;
    }

    /**
     * Gets templateEngine
     *
     * @return \UniOne\Model\TemplateEngineString|null
     */
    public function getTemplateEngine()
    {
        return $this->container['templateEngine'];
    }

    /**
     * Sets templateEngine
     *
     * @param \UniOne\Model\TemplateEngineString|null $templateEngine templateEngine
     *
     * @return self
     */
    public function setTemplateEngine($templateEngine)
    {
        if (is_null($templateEngine)) {
            throw new \InvalidArgumentException('non-nullable templateEngine cannot be null');
        }
        $this->container['templateEngine'] = $templateEngine;

        return $this;
    }

    /**
     * Gets globalSubstitutions
     *
     * @return array<string,string>|null
     */
    public function getGlobalSubstitutions()
    {
        return $this->container['globalSubstitutions'];
    }

    /**
     * Sets globalSubstitutions
     *
     * @param array<string,string>|null $globalSubstitutions Object for passing the substitutions(merge tags) common for all recipients - e.g., company name. If the substitution names are duplicated in object **substitutions**, the values of the variables will be taken from the object **substitutions**. The substitutions can be used in the following parameters:<br><br>* body.html* body.plaintext* body.amp* subject* from_name* options.unsubscribe_url<br><br>A substitution name can consist from latin characeters, numbers and **_** symbol, and should start with the letter.
     *
     * @return self
     */
    public function setGlobalSubstitutions($globalSubstitutions)
    {
        if (is_null($globalSubstitutions)) {
            throw new \InvalidArgumentException('non-nullable globalSubstitutions cannot be null');
        }
        $this->container['globalSubstitutions'] = $globalSubstitutions;

        return $this;
    }

    /**
     * Gets globalMetadata
     *
     * @return array<string,string>|null
     */
    public function getGlobalMetadata()
    {
        return $this->container['globalMetadata'];
    }

    /**
     * Sets globalMetadata
     *
     * @param array<string,string>|null $globalMetadata Object for passing the metadata common for all the recipients, such as **key**: **value**. Max key quantity: 10. Max key length: 64 symbols. Max value length: 1024 symbols. The metadata is returned by [webhook](https://docs.unione.io/en/web-api-ref#webhook). To group single emails into a campaign, you can use the system key 'campaign_id' with a value in the form of a non-negative decimal integer up to 128 bits or a UUID in the format 'c7703772-453e-4c77-a9ae-9a1b94051b5a'. Incorrect values will be treated as '0'.
     *
     * @return self
     */
    public function setGlobalMetadata($globalMetadata)
    {
        if (is_null($globalMetadata)) {
            throw new \InvalidArgumentException('non-nullable globalMetadata cannot be null');
        }
        $this->container['globalMetadata'] = $globalMetadata;

        return $this;
    }

    /**
     * Gets body
     *
     * @return \UniOne\Model\BodyObject
     */
    public function getBody()
    {
        return $this->container['body'];
    }

    /**
     * Sets body
     *
     * @param \UniOne\Model\BodyObject $body body
     *
     * @return self
     */
    public function setBody($body)
    {
        if (is_null($body)) {
            throw new \InvalidArgumentException('non-nullable body cannot be null');
        }
        $this->container['body'] = $body;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string|null
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string|null $subject Email subject.
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets fromEmail
     *
     * @return string
     */
    public function getFromEmail()
    {
        return $this->container['fromEmail'];
    }

    /**
     * Sets fromEmail
     *
     * @param string $fromEmail Sender's email.
     *
     * @return self
     */
    public function setFromEmail($fromEmail)
    {
        if (is_null($fromEmail)) {
            throw new \InvalidArgumentException('non-nullable fromEmail cannot be null');
        }
        $this->container['fromEmail'] = $fromEmail;

        return $this;
    }

    /**
     * Gets fromName
     *
     * @return string|null
     */
    public function getFromName()
    {
        return $this->container['fromName'];
    }

    /**
     * Sets fromName
     *
     * @param string|null $fromName Sender's name.
     *
     * @return self
     */
    public function setFromName($fromName)
    {
        if (is_null($fromName)) {
            throw new \InvalidArgumentException('non-nullable fromName cannot be null');
        }
        $this->container['fromName'] = $fromName;

        return $this;
    }

    /**
     * Gets replyTo
     *
     * @return string|null
     */
    public function getReplyTo()
    {
        return $this->container['replyTo'];
    }

    /**
     * Sets replyTo
     *
     * @param string|null $replyTo Optional Reply-To email (in case it's different to sender's email)
     *
     * @return self
     */
    public function setReplyTo($replyTo)
    {
        if (is_null($replyTo)) {
            throw new \InvalidArgumentException('non-nullable replyTo cannot be null');
        }
        $this->container['replyTo'] = $replyTo;

        return $this;
    }

    /**
     * Gets replyToName
     *
     * @return string|null
     */
    public function getReplyToName()
    {
        return $this->container['replyToName'];
    }

    /**
     * Sets replyToName
     *
     * @param string|null $replyToName Optional Reply-To name (if reply_to email is specified and you want to display not only this email but also the name)
     *
     * @return self
     */
    public function setReplyToName($replyToName)
    {
        if (is_null($replyToName)) {
            throw new \InvalidArgumentException('non-nullable replyToName cannot be null');
        }
        $this->container['replyToName'] = $replyToName;

        return $this;
    }

    /**
     * Gets trackLinks
     *
     * @return \UniOne\Model\TrackLinksInteger|null
     */
    public function getTrackLinks()
    {
        return $this->container['trackLinks'];
    }

    /**
     * Sets trackLinks
     *
     * @param \UniOne\Model\TrackLinksInteger|null $trackLinks trackLinks
     *
     * @return self
     */
    public function setTrackLinks($trackLinks)
    {
        if (is_null($trackLinks)) {
            throw new \InvalidArgumentException('non-nullable trackLinks cannot be null');
        }
        $this->container['trackLinks'] = $trackLinks;

        return $this;
    }

    /**
     * Gets trackRead
     *
     * @return \UniOne\Model\TrackReadInteger|null
     */
    public function getTrackRead()
    {
        return $this->container['trackRead'];
    }

    /**
     * Sets trackRead
     *
     * @param \UniOne\Model\TrackReadInteger|null $trackRead trackRead
     *
     * @return self
     */
    public function setTrackRead($trackRead)
    {
        if (is_null($trackRead)) {
            throw new \InvalidArgumentException('non-nullable trackRead cannot be null');
        }
        $this->container['trackRead'] = $trackRead;

        return $this;
    }

    /**
     * Gets headers
     *
     * @return \UniOne\Model\HeadersObject|null
     */
    public function getHeaders()
    {
        return $this->container['headers'];
    }

    /**
     * Sets headers
     *
     * @param \UniOne\Model\HeadersObject|null $headers headers
     *
     * @return self
     */
    public function setHeaders($headers)
    {
        if (is_null($headers)) {
            throw new \InvalidArgumentException('non-nullable headers cannot be null');
        }
        $this->container['headers'] = $headers;

        return $this;
    }

    /**
     * Gets attachments
     *
     * @return \UniOne\Model\AttachmentsArrayInner[]|null
     */
    public function getAttachments()
    {
        return $this->container['attachments'];
    }

    /**
     * Sets attachments
     *
     * @param \UniOne\Model\AttachmentsArrayInner[]|null $attachments Optional array of attachments
     *
     * @return self
     */
    public function setAttachments($attachments)
    {
        if (is_null($attachments)) {
            throw new \InvalidArgumentException('non-nullable attachments cannot be null');
        }
        $this->container['attachments'] = $attachments;

        return $this;
    }

    /**
     * Gets inlineAttachments
     *
     * @return \UniOne\Model\InlineAttachmentsArrayInner[]|null
     */
    public function getInlineAttachments()
    {
        return $this->container['inlineAttachments'];
    }

    /**
     * Sets inlineAttachments
     *
     * @param \UniOne\Model\InlineAttachmentsArrayInner[]|null $inlineAttachments Optional array of inline attachments, e.g. for including images in email instead of loading them from external URL.
     *
     * @return self
     */
    public function setInlineAttachments($inlineAttachments)
    {
        if (is_null($inlineAttachments)) {
            throw new \InvalidArgumentException('non-nullable inlineAttachments cannot be null');
        }
        $this->container['inlineAttachments'] = $inlineAttachments;

        return $this;
    }

    /**
     * Gets created
     *
     * @return string
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param string $created Template creation date and time in UTC timezone in format **YYYY-MM-DD hh:mm:ss**
     *
     * @return self
     */
    public function setCreated($created)
    {
        if (is_null($created)) {
            throw new \InvalidArgumentException('non-nullable created cannot be null');
        }
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets userId
     *
     * @return int
     */
    public function getUserId()
    {
        return $this->container['userId'];
    }

    /**
     * Sets userId
     *
     * @param int $userId Unique user identifier.
     *
     * @return self
     */
    public function setUserId($userId)
    {
        if (is_null($userId)) {
            throw new \InvalidArgumentException('non-nullable userId cannot be null');
        }
        $this->container['userId'] = $userId;

        return $this;
    }

    /**
     * Gets projectId
     *
     * @return string|null
     */
    public function getProjectId()
    {
        return $this->container['projectId'];
    }

    /**
     * Sets projectId
     *
     * @param string|null $projectId Unqiue project identifier, ASCII string up to 36 characters long.
     *
     * @return self
     */
    public function setProjectId($projectId)
    {
        if (is_null($projectId)) {
            throw new \InvalidArgumentException('non-nullable projectId cannot be null');
        }
        $this->container['projectId'] = $projectId;

        return $this;
    }

    /**
     * Gets projectName
     *
     * @return string|null
     */
    public function getProjectName()
    {
        return $this->container['projectName'];
    }

    /**
     * Sets projectName
     *
     * @param string|null $projectName Project name, unique for user account.
     *
     * @return self
     */
    public function setProjectName($projectName)
    {
        if (is_null($projectName)) {
            throw new \InvalidArgumentException('non-nullable projectName cannot be null');
        }
        $this->container['projectName'] = $projectName;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


