<?php
/**
 * WebhookSetRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Web API
 *
 * All UniOne API methods require HTTPS connection. UniOne accepts HTTP POST requests in JSON format up to 10 megabytes long and returns HTTP response also in JSON. API endpoint (or base URL) depends on which datacenter the user is registered at.<br>The preferred way is to use https://api.unione.io/en/transactional/api/v1 endpoint, but also you can use https://eu1.unione.io/en/transactional/api/v1 or https://us1.unione.io/en/transactional/api/v1 directly, depending on the host your account was registered at.
 *
 * The version of the OpenAPI document: 1.76
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace UniOne\Model;

use \ArrayAccess;
use \UniOne\ObjectSerializer;

/**
 * WebhookSetRequest Class Doc Comment
 *
 * @category Class
 * @package  UniOne
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WebhookSetRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'webhook_set_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'url' => 'string',
        'status' => '\UniOne\Model\WebhookStatusString',
        'eventFormat' => '\UniOne\Model\WebhookEventFormatString',
        'deliveryInfo' => '\UniOne\Model\WebhookDeliveryInfoInteger',
        'singleEvent' => '\UniOne\Model\WebhookSingleEventInteger',
        'maxParallel' => 'int',
        'events' => '\UniOne\Model\WebhookEventsObject'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'url' => 'uri',
        'status' => null,
        'eventFormat' => null,
        'deliveryInfo' => null,
        'singleEvent' => null,
        'maxParallel' => null,
        'events' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'url' => false,
        'status' => false,
        'eventFormat' => false,
        'deliveryInfo' => false,
        'singleEvent' => false,
        'maxParallel' => false,
        'events' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'url' => 'url',
        'status' => 'status',
        'eventFormat' => 'event_format',
        'deliveryInfo' => 'delivery_info',
        'singleEvent' => 'single_event',
        'maxParallel' => 'max_parallel',
        'events' => 'events'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'url' => 'setUrl',
        'status' => 'setStatus',
        'eventFormat' => 'setEventFormat',
        'deliveryInfo' => 'setDeliveryInfo',
        'singleEvent' => 'setSingleEvent',
        'maxParallel' => 'setMaxParallel',
        'events' => 'setEvents'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'url' => 'getUrl',
        'status' => 'getStatus',
        'eventFormat' => 'getEventFormat',
        'deliveryInfo' => 'getDeliveryInfo',
        'singleEvent' => 'getSingleEvent',
        'maxParallel' => 'getMaxParallel',
        'events' => 'getEvents'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('eventFormat', $data ?? [], null);
        $this->setIfExists('deliveryInfo', $data ?? [], null);
        $this->setIfExists('singleEvent', $data ?? [], null);
        $this->setIfExists('maxParallel', $data ?? [], 10);
        $this->setIfExists('events', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if (!is_null($this->container['maxParallel']) && ($this->container['maxParallel'] > 100)) {
            $invalidProperties[] = "invalid value for 'maxParallel', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['maxParallel']) && ($this->container['maxParallel'] < 5)) {
            $invalidProperties[] = "invalid value for 'maxParallel', must be bigger than or equal to 5.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url URL that will receive the notification when an event occurs. The URL should be unique for a user or a project. Only ASCII characters are supported for now in URL, please convert to [Punycode](https://en.wikipedia.org/wiki/Punycode) if you need to use non-ASCII characters.
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \UniOne\Model\WebhookStatusString|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \UniOne\Model\WebhookStatusString|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets eventFormat
     *
     * @return \UniOne\Model\WebhookEventFormatString|null
     */
    public function getEventFormat()
    {
        return $this->container['eventFormat'];
    }

    /**
     * Sets eventFormat
     *
     * @param \UniOne\Model\WebhookEventFormatString|null $eventFormat eventFormat
     *
     * @return self
     */
    public function setEventFormat($eventFormat)
    {
        if (is_null($eventFormat)) {
            throw new \InvalidArgumentException('non-nullable eventFormat cannot be null');
        }
        $this->container['eventFormat'] = $eventFormat;

        return $this;
    }

    /**
     * Gets deliveryInfo
     *
     * @return \UniOne\Model\WebhookDeliveryInfoInteger|null
     */
    public function getDeliveryInfo()
    {
        return $this->container['deliveryInfo'];
    }

    /**
     * Sets deliveryInfo
     *
     * @param \UniOne\Model\WebhookDeliveryInfoInteger|null $deliveryInfo deliveryInfo
     *
     * @return self
     */
    public function setDeliveryInfo($deliveryInfo)
    {
        if (is_null($deliveryInfo)) {
            throw new \InvalidArgumentException('non-nullable deliveryInfo cannot be null');
        }
        $this->container['deliveryInfo'] = $deliveryInfo;

        return $this;
    }

    /**
     * Gets singleEvent
     *
     * @return \UniOne\Model\WebhookSingleEventInteger|null
     */
    public function getSingleEvent()
    {
        return $this->container['singleEvent'];
    }

    /**
     * Sets singleEvent
     *
     * @param \UniOne\Model\WebhookSingleEventInteger|null $singleEvent singleEvent
     *
     * @return self
     */
    public function setSingleEvent($singleEvent)
    {
        if (is_null($singleEvent)) {
            throw new \InvalidArgumentException('non-nullable singleEvent cannot be null');
        }
        $this->container['singleEvent'] = $singleEvent;

        return $this;
    }

    /**
     * Gets maxParallel
     *
     * @return int|null
     */
    public function getMaxParallel()
    {
        return $this->container['maxParallel'];
    }

    /**
     * Sets maxParallel
     *
     * @param int|null $maxParallel Maximum quantity of permitted parallel queries to your server. The more your server can handle - the better.
     *
     * @return self
     */
    public function setMaxParallel($maxParallel)
    {
        if (is_null($maxParallel)) {
            throw new \InvalidArgumentException('non-nullable maxParallel cannot be null');
        }

        if (($maxParallel > 100)) {
            throw new \InvalidArgumentException('invalid value for $maxParallel when calling WebhookSetRequest., must be smaller than or equal to 100.');
        }
        if (($maxParallel < 5)) {
            throw new \InvalidArgumentException('invalid value for $maxParallel when calling WebhookSetRequest., must be bigger than or equal to 5.');
        }

        $this->container['maxParallel'] = $maxParallel;

        return $this;
    }

    /**
     * Gets events
     *
     * @return \UniOne\Model\WebhookEventsObject|null
     */
    public function getEvents()
    {
        return $this->container['events'];
    }

    /**
     * Sets events
     *
     * @param \UniOne\Model\WebhookEventsObject|null $events events
     *
     * @return self
     */
    public function setEvents($events)
    {
        if (is_null($events)) {
            throw new \InvalidArgumentException('non-nullable events cannot be null');
        }
        $this->container['events'] = $events;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


